version: '2'

services:

    prometheus-app:
        build: ./apache-traffic-server-exporter/
        ports:
            - '8080:8080'
        links:
            - prometheus
       
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'

    graphana:
        image: grafana/grafana
        ports:
            - '3000:3000'
        links:
            - prometheus

    node-exporter:
        image: prom/node-exporter:0.12.0rc1
        ports:
            - '9100:9100'
